const SERVER_ERRORS = {
    USER_IS_ALREADY_EXIST: 1000,

    RECORDS_NOT_FOUND: 3000,
    RECORD_NOT_FOUND: 3001,
    RECORD_EMPTY: 3002,
    RECORD_IS_EXIST_ALREADY: 3018,
    RECORD_IS_NOT_VALID: 3019,
  };
  
  module.exports = SERVER_ERRORS;